[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
mini-redis = "0.4"
bytes = "1"
futures = "0.3"
crossbeam = "0.8"
